### ISSUE TITLE
Implementar free_queue()

### ISSUE THREAD

**Issue by Kludex** [viagostini/Sistemas-Operacionais#5]

**Comment by viagostini** [comment]
Implementei o seguinte:

    void free_queue(Queue q) {
        Node tmp;
        while (q->size != 0) {
            tmp = dequeue(q);
            free(tmp);
        }
        free(q);
    }

Mas precisa de testes (eu testei  com outros tipos de struct e deu certo, mas n tenho certeza pra Process)
